### ISSUE TITLE
"\x84" from ASCII-8BIT to UTF-8 during upload_file

### ISSUE THREAD

**Issue by glappen** [bo-oz/vimeo_me2#16]
Hello,

I started having this issue recently and no longer can upload files to my vimeo account using the API.  The code basically looks like this:

```
vimeo_client = VimeoMe2::User.new(Rails.application.config.vimeo_token)                                                                                                                                    
vid_id = vimeo_client.upload_video(video_file)
```

The error I get is "Encoding::UndefinedConversionError: "\x84" from ASCII-8BIT to UTF-8.  Here is the stack trace:

```
activesupport (5.1.6) lib/active_support/core_ext/object/json.rb:36:in `encode'
activesupport (5.1.6) lib/active_support/core_ext/object/json.rb:36:in `to_json'
activesupport (5.1.6) lib/active_support/core_ext/object/json.rb:36:in `to_json'
activesupport (5.1.6) lib/active_support/json/encoding.rb:55:in `to_json'
/usr/local/lib/ruby/2.4.0/json/common.rb:224:in `generate'
/usr/local/lib/ruby/2.4.0/json/common.rb:224:in `generate'
activesupport (5.1.6) lib/active_support/json/encoding.rb:100:in `stringify'
activesupport (5.1.6) lib/active_support/json/encoding.rb:33:in `encode'
activesupport (5.1.6) lib/active_support/json/encoding.rb:20:in `encode'
activesupport (5.1.6) lib/active_support/core_ext/object/json.rb:39:in `to_json'
/gems/2.4.1/bundler/gems/vimeo_me2-6960e41a4a5a/lib/vimeo_me2/http/http_request.rb:72:in `http_request'
/gems/2.4.1/bundler/gems/vimeo_me2-6960e41a4a5a/lib/vimeo_me2/http/http_request.rb:21:in `make_http_request'
/gems/2.4.1/bundler/gems/vimeo_me2-6960e41a4a5a/lib/vimeo_me2/base.rb:36:in `request'
/gems/2.4.1/bundler/gems/vimeo_me2-6960e41a4a5a/lib/vimeo_me2/base.rb:16:in `block (2 levels) in <class:VimeoObject>'
/gems/2.4.1/bundler/gems/vimeo_me2-6960e41a4a5a/lib/vimeo_me2/user/upload.rb:57:in `start_upload'
/gems/2.4.1/bundler/gems/vimeo_me2-6960e41a4a5a/lib/vimeo_me2/user/upload.rb:34:in `handle_upload'
/gems/2.4.1/bundler/gems/vimeo_me2-6960e41a4a5a/lib/vimeo_me2/user/upload.rb:11:in `upload_video'
app/models/component.rb:56:in `upload_hosted_file'
```

video_file is a ActionDispatch::Http::UploadedFile with content-type "video/mp4".  Any idea why this would stop working, or if there is another way to accomplish the upload?  Thank you very much for any help, and for making this gem in the first place  - it is very helpful.

Greg

**Comment by bo-oz** [comment]
Have you tried another file? It seems to have something to do with the JSON, although this stack trace is not really helping to determine where this goes wrong. Could it be a strange character in the video title?

**Comment by bo-oz** [comment]
Nevermind, I get the same error. Let me do some research what's going on. Maybe something got changed in the response of the webserver.

**Comment by glappen** [comment]
I have some more information that might be helpful - I started getting this error when I upgraded from version 1.1.3 to 1.1.4.  I upgraded because I started getting a different error and I thought upgrading might fix it.  The error was: "Something went wrong" - I debugged it a bit and found myself looking at lib/vimeo_me2/user/upload.rb.  It was getting a 405 error when it called verify_upload because @ticket['upload_link_secure'] was nil.  It was nil even on line 11 right after calling get_upload_ticket.  I suspect something change on the vimeo side that is breaking this.

**Comment by bo-oz** [comment]
I don't think a lot has changed on the upload code between 1.1.3 and 1.1.4. I checked the procedure, but it is getting a valid upload ticket on my local machine. 

Somehow the HTTParty request fails with that error, it is not raised by this gem. I honestly have no clue what Encoding::UndefinedConversionError means. Would love to fix this bug, but could use some expert opinion on this!

**Comment by glappen** [comment]
That error seems to come when it encodes the request to JSON - it's calling to_json on the binary string.  I think I know why:

https://github.com/bo-oz/vimeo_me2/commit/c7bd85bfef8984c55b87f0f9de4a186a3cc13196#diff-1f9805fd1d01ad8e6b7b85a0887df1d1R67
```
 @body = @body.to_json if @headers['Content-Type'] = 'application/json'
```

change the = to == ?

**Comment by glappen** [comment]
I fixed it and submitted a PR:

https://github.com/bo-oz/vimeo_me2/pull/17

Thanks!

**Comment by bo-oz** [comment]
Great, thanks. I accepted this as a PR a while back. Stupid I missed that one. Thanks for finding and fixing!

**Comment by bo-oz** [comment]
I think there is still an issue, since the name change is not happening. The request returns an error: An unknown error has occurred. Please let us know! Are you experiencing the same? The video uploads fine now.

**Comment by bo-oz** [comment]
I think this is due to some kind of issue with the Vimeo API, I raised a bug report with them. Let's see how this is dealt with. @jamiew, are you still with Vimeo and able to support?

**Comment by jamiew** [comment]
No longer with Vimeo but happy to help escalate if you don’t hear back quickly. Lmk

**Comment by bo-oz** [comment]
I manually removed the privacy key before updating the name. I also updated the code so it utilizes the 3.4 API. Please check this branch, if you'd like to test it: https://github.com/bo-oz/vimeo_me2/tree/3.4-upload

**Comment by glappen** [comment]
I tested and opened a new issue as the new issue is unrelated to this original problem:  https://github.com/bo-oz/vimeo_me2/issues/18

**Comment by bo-oz** [comment]
I got the following reponse from Vimeo:

> I have ticketed this issue with our API team. Indeed, we should ignore the "download" value in the PATCH request when the user is Basic, and return a specific error message here.

I'll let you know if we have any news to share!
Sincerely,

Let's hope this solves the issue eventually. For now the privacy parameters are surpressed, so as long as no-one is needing those, we are fine! Okay to close this issue?
